dist: xenial
language: python
python:
- '3.6'
branches:
  only:
  - master
  - "/\\d+\\.\\d+\\.\\d+/"
jobs:
  include:
  - stage: test
    install: pip install tox
    script: tox -e flake8
  - install: pip install tox
    script: tox -e behave
  - install: pip install tox
    script: tox -e tanguan
  - stage: deploy
    provider: pypi
    skip_cleanup: true
    user: a8568730
    password:
      secure: EGtXvcivUqzPOBk4INGsH2dNUC3qyBmCe+P9vVbG/yvra5dqchU+46NYdInugRG64jyNzqW8peo7SriRjZ3IKz/id9rK2UnVayvd7eVz098WJVhEV3qyYScZ9v99v8ID+Suy8Nii1X1fAaJ8rALDA+jpfIo6z0mfSjitrp6WJlI1n23g2M+9g2UMgcM299gm4qBOcbqVuCjo6F4mCgKDuDovtjixzu9H6Yn/BbdKCNVy4xlhfecw3qGuJJczRr9ubKzQcIAkoRJsj564JM7qoxr/MH/55z3nRt4jwPSRj8rmX/yQgmFrqIdW7MXLgx06kfJw3aJvYM/R3KiQHwnMiVGjTyDBRXajR5agWiWKqNYn9RVUny2AjIYq4h7L3GbwaURaRFo1fFw/1CIaFG+968svbsBsT/p4NWpRPk5jX2RkLi4hfw1nk14lvPNyd07GTeTHoF2S4vAsHZcvF5zDEajJkqSk1pB+fMuMMenoa+CpfciorHHyDnSmZOZjbCVBo0Y4vZYIbB8oNHovKxw139VNUJJVExFIWarpXT8nPNoQNJ9l5zemn2aXw/xezNoVRCZYDwhGo31fUXRNt1R9bAxH8nBxMe7yGiGqLjkM7OV1RjHnz0H6EXxD1n3jr9Ybrk+eg6T3Ds4kKuBSEofo8qDPI35koC8aDAgwhvWLoIo=
      on:
        tags: true
        distributions: sdist bdist_wheel
        repo: i3thuan5/KeSi
